server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Appels API relayés vers le conteneur backend
    # Envoi de photos / justificatifs (10 Mo max côté API)
    client_max_body_size 12m;

    location /api/ {
        proxy_pass http://api:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Routage Angular (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
